# Generated by Django 6.0.2 on 2026-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dashboardstats_userprofile_userskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google OAuth')], default='email', help_text='Authentication method used', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth user ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_picture',
            field=models.URLField(blank=True, help_text='Google profile picture URL', max_length=500, null=True),
        ),
    ]
