# Generated by Django 6.0.2 on 2026-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_update_aggregated_job_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aggregatedjob',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aggregatedjob',
            name='source',
            field=models.CharField(choices=[('JSearch', 'JSearch'), ('Remotive', 'Remotive'), ('Arbeitnow', 'Arbeitnow'), ('Adzuna', 'Adzuna')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedjob',
            unique_together={('title', 'company', 'source')},
        ),
        migrations.AddIndex(
            model_name='aggregatedjob',
            index=models.Index(fields=['is_active', '-created_at'], name='jobs_aggreg_is_acti_39e91f_idx'),
        ),
    ]
